### PR TITLE
update: refetch selectable targets while dragging to support lazy loading

### PR DESCRIPTION
**Pull request by junqdu**
#41

### CODE REVIEW

**Comment by junqdu** [comment]
@daybrush for review

**Comment by junqdu** [comment]
@sibbng can you review?

**Comment by daybrush** [comment]
@junqdu 

Sorry.  If you call the method every time, there is a performance problem.

Add code that calls that method`selecto.findSelectableTargets()` when lazy loading is done from the outside.

Like:
https://github.com/naver/egjs-imready

**Comment by junqdu** [comment]
@daybrush thanks! Using ref and calling the method you mentioned worked!

**Pull request closed without merging**
